## numpy기초연습문제

In [2]:
import numpy as np

In [4]:
a = np.zeros((3, 4))
a #zerprs를 통해 값이0인 array 생성

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a # 반복문을 통해 a어레이에 값 채우기

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [7]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a #반복문을 통해 array값 변경 

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [8]:
a[1, 2] #특정 값 추출

7.0

In [13]:
a.shape

(3, 4)

In [12]:
a[[1], :] #1행출력

array([[5., 6., 7., 8.]])

In [14]:
a[:,[0, 2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

In [15]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result #6보다작은수출력

array([1., 2., 3., 4., 5., 6.])

In [17]:
a[a <= 6] #6보다작은수출력

array([1., 2., 3., 4., 5., 6.])

In [19]:
b = np.random.random((3, 4))
b #무작위출력

array([[0.73998972, 0.44811193, 0.34093188, 0.75968756],
       [0.29332591, 0.45146375, 0.15753513, 0.30284398],
       [0.13257046, 0.37777749, 0.14125491, 0.35857324]])

In [21]:
c = a * b
c #변수 c에 a와b의 곱을 값으로 설정

array([[0.73998972, 0.89622386, 1.02279563, 3.03875026],
       [1.46662954, 2.70878252, 1.10274589, 2.42275187],
       [1.19313411, 3.77777495, 1.55380397, 4.30287885]])

In [23]:
d = b.T
d #b의 전치행렬을 변수d에 설정

array([[0.73998972, 0.29332591, 0.13257046],
       [0.44811193, 0.45146375, 0.37777749],
       [0.34093188, 0.15753513, 0.14125491],
       [0.75968756, 0.30284398, 0.35857324]])

In [24]:
d.shape

(4, 3)

In [25]:
print(a.shape, d.shape) #각 차원의 크기 구하기

(3, 4) (4, 3)


In [26]:
e = a.dot(d)
e #행렬의 곱을 e에 저장

array([[ 5.69775947,  2.88023473,  2.74618312],
       [14.85264384,  7.70090982,  6.7868875 ],
       [24.00752821, 12.52158492, 10.82759188]])

In [27]:
np.sum(e, axis=1) #열의 합 계산

array([11.32417732, 29.34044116, 47.356705  ])