# 실습과제 만들기

In [22]:
import numpy as np
import pandas as pd

In [26]:
people=pd.read_csv(r"ex2.csv")
people

사용월  호선명 지하철역  04시-05시 승차인원  04시-05시 하차인원  05시-06시 승차인원  \
0      202008  1호선  동대문           408             7         11140   
1      202008  1호선  동묘앞           100             2          2908   
2      202008  1호선  서울역           696            14          8106   
3      202008  1호선   시청            24             0          1603   
4      202008  1호선  신설동           207             9          8294   
...       ...  ...  ...           ...           ...           ...   
39280  201501  중앙선  운길산             0             0           177   
39281  201501  중앙선   원덕             1             0           292   
39282  201501  중앙선   중랑            14             1          4929   
39283  201501  중앙선   팔당             0             0           161   
39284  201501  중앙선   회기           436             3         10929   

       05시-06시 하차인원  06시-07시 승차인원  06시-07시 하차인원  07시-08시 승차인원  ...  \
0              1807          7803          5728         11446  ...   
1               792          2969          3639          4948  ...   
2              5956         10320         32911         28966  ...   
3              3407          2801         16891          5484  ...   
4              1958          7880          7277         14953  ...   
...             ...           ...           ...           ...  ...   
39280            56           642           403          1292  ...   
39281             4           415            46           537  ...   
39282           424          8539          2084         22160  ...   
39283            50           368           149          1227  ...   
39284          3067         23317         10430         65043  ...   

       23시-24시 하차인원  00시-01시 승차인원  00시-01시 하차인원  01시-02시 승차인원  01시-02시 하차인원  \
0              8744            34           838             0             0   
1              2699             4          1273             0             1   
2             10223            22           910             0             0   
3              1547             4            50             0             0   
4              6387            18           508             0             0   
...             ...           ...           ...           ...           ...   
39280           633             3           222             0             0   
39281           383             3           157             0             0   
39282          6501            86          1617             0             0   
39283           336             8            85             0             0   
39284         35702           767          9314             0             0   

       02시-03시 승차인원  02시-03시 하차인원  03시-04시 승차인원  03시-04시 하차인원      작업일자  
0                 2             0             0             0  20200903  
1                 0             0             0             0  20200903  
2                 0             0             0             0  20200903  
3                 0             0             0             0  20200903  
4                 0             0             0             0  20200903  
...             ...           ...           ...           ...       ...  
39280             0             0             0             0  20151223  
39281             0             0             0             0  20151223  
39282             0             0             0             0  20151223  
39283             0             0             0             0  20151223  
39284             0             0             0             0  20151223  

[39285 rows x 52 columns]

##### 1.행의갯수와 열의 갯수 보기

In [31]:
people.shape

(39285, 52)

#### 2.필요한 데이터만 추출하기

In [45]:
commute=people[["사용월","지하철역","06시-07시 승차인원",'06시-07시 하차인원',"07시-08시 승차인원","07시-08시 하차인원","18시-19시 승차인원","18시-19시 하차인원",
       "19시-20시 승차인원","19시-20시 하차인원"]]
commute

사용월 지하철역  06시-07시 승차인원  06시-07시 하차인원  07시-08시 승차인원  07시-08시 하차인원  \
0      202008  동대문          7803          5728         11446          9849   
1      202008  동묘앞          2969          3639          4948          7650   
2      202008  서울역         10320         32911         28966         78449   
3      202008   시청          2801         16891          5484         53421   
4      202008  신설동          7880          7277         14953         20102   
...       ...  ...           ...           ...           ...           ...   
39280  201501  운길산           642           403          1292           675   
39281  201501   원덕           415            46           537           248   
39282  201501   중랑          8539          2084         22160          3027   
39283  201501   팔당           368           149          1227           523   
39284  201501   회기         23317         10430         65043         24473   

       18시-19시 승차인원  18시-19시 하차인원  19시-20시 승차인원  19시-20시 하차인원  
0             20320         16623         14422         17199  
1             19924          9424          9783          5869  
2            163421         59707         82628         43126  
3            114019         12570         42315          6716  
4             49834         23748         19190         16518  
...             ...           ...           ...           ...  
39280          2304          1218          1332          1457  
39281           563           721           175           714  
39282          8399         19547          6449         21424  
39283          1617           822           845           749  
39284         59218         76039         38996         81870  

[39285 rows x 10 columns]

#### 3. 열의 이름 바꾸기

In [107]:
commute = commute.rename(columns={"06시-07시 승차인원":"오전 승차"})
commute = commute.rename(columns={"07시-08시 승차인원":"오전 승차"})
commute = commute.rename(columns={"06시-07시 하차인원":"오전 하차"})
commute = commute.rename(columns={"07시-08시 하차인원":"오전 하차"})
commute = commute.rename(columns={"18시-19시 승차인원":"오후 승차"})
commute = commute.rename(columns={"18시-19시 하차인원":"오후 하차"})
commute = commute.rename(columns={"19시-20시 승차인원":"오후 승차"})
commute = commute.rename(columns={"19시-20시 하차인원":"오후 하차"})
commute

사용월 지하철역  오전 승차  오전 하차  오전 승차  오전 하차   오후 승차  오후 하차  오후 승차  오후 하차
0      202008  동대문   7803   5728  11446   9849   20320  16623  14422  17199
1      202008  동묘앞   2969   3639   4948   7650   19924   9424   9783   5869
2      202008  서울역  10320  32911  28966  78449  163421  59707  82628  43126
3      202008   시청   2801  16891   5484  53421  114019  12570  42315   6716
4      202008  신설동   7880   7277  14953  20102   49834  23748  19190  16518
...       ...  ...    ...    ...    ...    ...     ...    ...    ...    ...
39280  201501  운길산    642    403   1292    675    2304   1218   1332   1457
39281  201501   원덕    415     46    537    248     563    721    175    714
39282  201501   중랑   8539   2084  22160   3027    8399  19547   6449  21424
39283  201501   팔당    368    149   1227    523    1617    822    845    749
39284  201501   회기  23317  10430  65043  24473   59218  76039  38996  81870

[39285 rows x 10 columns]

#### 4. 데이터 타입보기

In [99]:
commute.dtypes

사용월       int64
지하철역     object
오전 승차     int64
오전 하차     int64
오전 승차     int64
오전 하차     int64
오후 승차     int64
오후 하차     int64
오후 승차     int64
오후 하차     int64
dtype: object

In [60]:
commute.head()

사용월 지하철역  오전 승차  오전 하차  오전 승차  오전 하차   오후 승차  오후 하차  오후 승차  오후 하차
0  202008  동대문   7803   5728  11446   9849   20320  16623  14422  17199
1  202008  동묘앞   2969   3639   4948   7650   19924   9424   9783   5869
2  202008  서울역  10320  32911  28966  78449  163421  59707  82628  43126
3  202008   시청   2801  16891   5484  53421  114019  12570  42315   6716
4  202008  신설동   7880   7277  14953  20102   49834  23748  19190  16518

In [47]:
#### 추출한 데이터의 자료구조 확인하기

In [48]:
print(type(commute))

<class 'pandas.core.frame.DataFrame'>


In [49]:
commute.describe()

사용월  06시-07시 승차인원  06시-07시 하차인원   07시-08시 승차인원  \
count   39285.000000  39285.000000  39285.000000   39285.000000   
mean   201746.410411  11097.295558   7352.395138   29151.490467   
std       163.709435  10981.291229   7939.777346   30208.741988   
min    201501.000000      0.000000      0.000000       0.000000   
25%    201606.000000   3529.000000   2399.000000    8250.000000   
50%    201711.000000   7879.000000   5044.000000   20144.000000   
75%    201904.000000  14965.000000   9369.000000   39428.000000   
max    202008.000000  99232.000000  87300.000000  294593.000000   

        07시-08시 하차인원   18시-19시 승차인원   18시-19시 하차인원   19시-20시 승차인원  \
count   39285.000000   39285.000000   39285.000000   39285.000000   
mean    16825.333359   37835.523202   33863.572050   22943.742854   
std     21703.347319   49614.952048   36560.783277   31209.372892   
min         0.000000       0.000000       0.000000       0.000000   
25%      4735.000000    9595.000000   10999.000000    5483.000000   
50%      9816.000000   21346.000000   23598.000000   12530.000000   
75%     19871.000000   44149.000000   42134.000000   27409.000000   
max    238513.000000  448390.000000  305922.000000  309645.000000   

        19시-20시 하차인원  
count   39285.000000  
mean    30968.709177  
std     33334.124391  
min         0.000000  
25%      9627.000000  
50%     21530.000000  
75%     39504.000000  
max    302536.000000

#### 5.numpy array로 변환하기

In [63]:
arr = commute.to_numpy()
arr

array([[202008, '동대문', 7803, ..., 16623, 14422, 17199],
       [202008, '동묘앞', 2969, ..., 9424, 9783, 5869],
       [202008, '서울역', 10320, ..., 59707, 82628, 43126],
       ...,
       [201501, '중랑', 8539, ..., 19547, 6449, 21424],
       [201501, '팔당', 368, ..., 822, 845, 749],
       [201501, '회기', 23317, ..., 76039, 38996, 81870]], dtype=object)

In [64]:
len(arr) #array 길이 확인

39285

#### 6.내림차순으로 정렬하기

In [66]:
commute.sort_index(axis=0, ascending=False) 

사용월 지하철역  오전 승차  오전 하차  오전 승차  오전 하차   오후 승차  오후 하차  오후 승차  오후 하차
39284  201501   회기  23317  10430  65043  24473   59218  76039  38996  81870
39283  201501   팔당    368    149   1227    523    1617    822    845    749
39282  201501   중랑   8539   2084  22160   3027    8399  19547   6449  21424
39281  201501   원덕    415     46    537    248     563    721    175    714
39280  201501  운길산    642    403   1292    675    2304   1218   1332   1457
...       ...  ...    ...    ...    ...    ...     ...    ...    ...    ...
4      202008  신설동   7880   7277  14953  20102   49834  23748  19190  16518
3      202008   시청   2801  16891   5484  53421  114019  12570  42315   6716
2      202008  서울역  10320  32911  28966  78449  163421  59707  82628  43126
1      202008  동묘앞   2969   3639   4948   7650   19924   9424   9783   5869
0      202008  동대문   7803   5728  11446   9849   20320  16623  14422  17199

[39285 rows x 10 columns]

#### 7.지하철 역별로 정렬

In [70]:
commute.sort_values(by='지하철역')

사용월       지하철역  오전 승차  오전 하차  오전 승차  오전 하차  오후 승차  오후 하차  오후 승차  \
16627  201805   4.19민주묘지   3094   1348   7353   1946   9554   7362   5134   
16038  201806   4.19민주묘지   2909   1396   7295   1955   6708   6804   4011   
17805  201803   4.19민주묘지   2840   1318   7141   1776   8981   7310   4333   
13091  201811   4.19민주묘지   3210   1072   8242   1868   8218   7590   4466   
4732   202001   4.19민주묘지   2570    772   7004   1396   3822   6689   2538   
...       ...        ...    ...    ...    ...    ...    ...    ...    ...   
25086  201702  흑석(중앙대입구)   5769   5020  16261  10441  20114  25419  13038   
23948  201704  흑석(중앙대입구)   7280   6600  19288  14226  28811  31360  18235   
3293   202003  흑석(중앙대입구)   4577   3973  12492   8563  13002  19957   7486   
21088  201709  흑석(중앙대입구)   7270   7341  19853  13716  32193  31397  18318   
1497   202006  흑석(중앙대입구)   5685   4797  15843  10510  15521  25120   9057   

       오후 하차  
16627   7927  
16038   7369  
17805   7463  
13091   7668  
4732    7285  
...      ...  
25086  24337  
23948  26016  
3293   14681  
21088  26031  
1497   17553  

[39285 rows x 10 columns]

####  9. loc, iloc을 이용한 인덱싱과 슬라이싱


In [77]:
commute.loc[commute['지하철역']=='동대문']

사용월 지하철역  오전 승차  오전 하차  오전 승차  오전 하차   오후 승차  오후 하차  오후 승차  오후 하차
0      202008  동대문   7803   5728  11446   9849   20320  16623  14422  17199
98     202008  동대문   2664  11228   4262  30999   59199   9946  26377  11769
597    202007  동대문   9547   7086  14555  12502   24896  20703  16744  21459
695    202007  동대문   3639  14667   5750  39626   80249  13508  33951  16860
1195   202006  동대문   9668   7451  14530  13436   23839  19307  16071  21241
...       ...  ...    ...    ...    ...    ...     ...    ...    ...    ...
37728  201503  동대문   6497  15639   7351  51116  111616  26804  59314  33184
38184  201502  동대문   9429   6530  14698  11785   33531  31203  24430  30813
38282  201502  동대문   4267  12034   4991  35465   88638  21713  45085  26185
38734  201501  동대문  10907   7588  16633  13326   36750  33513  25964  35239
38832  201501  동대문   5308  14566   5981  43598  107462  24853  52488  30218

[136 rows x 10 columns]

In [118]:
commute2=commute.reindex([7345,8233,226,4379,1235,4426,6237,121,178,34])
commute2

사용월        지하철역  오전 승차  오전 하차  오전 승차  오전 하차  오후 승차  오후 하차  오후 승차  \
7345  201908          구산  11039   2509  29234   5012  10927  20412   7008   
8233  201907          계양  25661   3227  70891   4387  10826  41073   6802   
226   202008    대림(구로구청)   7678   4076  13327   6394  17089  20292  11350   
4379  202001   안암(고대병원앞)   3166   5899   8878  13002  34238  22836  20694   
1235  202006          신촌  12503  14394  32808  35885  84767  93700  57254   
4426  202001  숭실대입구(살피재)  10897   4570  34643   6581  20771  45278  13021   
6237  201910        강동구청  11044   5737  35049  14360  29839  37412  12884   
121   202008          개롱   7077   3032  20769   6088  11871  17867   5601   
178   202008    대흥(서강대앞)   4747   3434  11887  10061  21160  17969  10347   
34    202008          신당  10320   6768  22779  14765  30295  37268  18733   

      오후 하차  
7345  20848  
8233  53646  
226   13535  
4379  19455  
1235  65659  
4426  38265  
6237  31456  
121   17460  
178   12972  
34    25847

#### 10. 조건에 따라 행 추출

In [119]:
commute2=commute2[commute2['사용월'] >202000]

In [120]:
commute2

사용월        지하철역  오전 승차  오전 하차  오전 승차  오전 하차  오후 승차  오후 하차  오후 승차  \
226   202008    대림(구로구청)   7678   4076  13327   6394  17089  20292  11350   
4379  202001   안암(고대병원앞)   3166   5899   8878  13002  34238  22836  20694   
1235  202006          신촌  12503  14394  32808  35885  84767  93700  57254   
4426  202001  숭실대입구(살피재)  10897   4570  34643   6581  20771  45278  13021   
121   202008          개롱   7077   3032  20769   6088  11871  17867   5601   
178   202008    대흥(서강대앞)   4747   3434  11887  10061  21160  17969  10347   
34    202008          신당  10320   6768  22779  14765  30295  37268  18733   

      오후 하차  
226   13535  
4379  19455  
1235  65659  
4426  38265  
121   17460  
178   12972  
34    25847

In [135]:
commute3=commute.reindex([1,2,3])
commute3

사용월 지하철역  오전 승차  오전 하차  오전 승차  오전 하차   오후 승차  오후 하차  오후 승차  오후 하차
1  202008  동묘앞   2969   3639   4948   7650   19924   9424   9783   5869
2  202008  서울역  10320  32911  28966  78449  163421  59707  82628  43126
3  202008   시청   2801  16891   5484  53421  114019  12570  42315   6716

#### commute3로 numpy함수를 사용하여 array 만들기

In [158]:
arr2 = commute3.to_numpy()
arr2

array([[202008, '동묘앞', 2969, 3639, 4948, 7650, 19924, 9424, 9783, 5869],
       [202008, '서울역', 10320, 32911, 28966, 78449, 163421, 59707, 82628,
        43126],
       [202008, '시청', 2801, 16891, 5484, 53421, 114019, 12570, 42315,
        6716]], dtype=object)

#### type 알아보기

In [137]:
type(arr2)

numpy.ndarray

#### array 세분화하기

In [156]:
a=(arr2[1,[2,3,4,5,6,7,8,9]])
b=(arr2[0,[2,3,4,5,6,7,8,9]])
print(a)
print(b)

[10320 32911 28966 78449 163421 59707 82628 43126]
[2969 3639 4948 7650 19924 9424 9783 5869]


#### 배열연산

In [160]:
print(a+b)

[13289 36550 33914 86099 183345 69131 92411 48995]


In [161]:
print(np.add(a,b))

[13289 36550 33914 86099 183345 69131 92411 48995]


In [162]:
print(np.sum(a))

499528


In [163]:
print(np.sum(b))

64206
